---

- name: copy service definition for Jenkins
  template:
    src: jenkins.service
    dest: "/etc/systemd/system/jenkins.service"
    mode: 0644
    owner: root
    group: root

- name: copy executable for Jenkins
  template:
    src: jenkins
    dest: "/usr/local/bin/jenkins"
    mode: 0755
    owner: root
    group: root
#
#- name: Update package lists
#  apt:
#    update_cache: yes

- name: Remove conflicting Docker GPG key file
  file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent

- name: Add GPG key for Jenkins repository
  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA

- name: Update package lists
  shell: sudo apt update


- name: Install containerd
  apt:
    name: containerd
    state: present


- name: Update containerd
  apt:
    name: containerd
    state: latest
  ignore_errors: yes


- name: Install Docker
  apt:
    name: docker.io
    state: present


- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: sleep
  pause:
    seconds: 10


- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: Ensure Java is installed.
  apt:
    name: "{{ java_packages }}"
    state: present
