---

- name: restart jenkins
  service:
    name: "jenkins.service"
    state: restarted
    enabled: true

- name: Restart docker.io
  service:
    name: "docker.io"
    state: restarted
    enabled: true
